Refactor UI (#87)
* refactor(ui): refactor UI to smaller components. Add useQuery lib for data fetching

fix #57, #84, #86

* ci(hooks): add license header validation to pre-commit hook

* refactor(ui): move all styled-components to separate style.tsx files

* style: fix all eslint issues that were consequences of adding new eslint rules/plugins in 7308aa9

* feat(ui): add Sentry.io for error monitoring. Minor refactors

Added Sentry.io for monitoring and tracing of (un)caught/(un)handled errors occuring
on the frontend.
Minor adjustments to some components where refactoring or code splitting were needed,
implement useQuery instead of useEffects.
Fixed bug in CreditsTable where if you selecteda (just one) course and then removed it instantly,
the master check table still rendered its credits etc. while removed (stale data).

* refactor: remove usage of SVG as RC. Bump pnpm deps. Refactor missing SC to styles.tsx

Using (SVG) icons as React Components (RC) is outdated and results in errors and slowdown. A long
term solution is to be found, until that, icons are just removed.  Many dependencies were out of
date, and with secuirty in regards, dependeices were bumped to latest versions and tested. Refactor
the last styled components to a separate styles.tsx file for full segretation between components and
styled elements.

* build(docker): add Dockerfile for production frontend

* build: optimize vite build process and SEO. Remove SVG from license checker

* feat: move filter state into CourseContext. Remove redundant and obsolete code

Filter state was widely used across the React application, thus it was moved in to the global
CourseContext rather than passed along the hierarchy (prop drilling). Remove JSX icons as they
prompted more issues than solutions. Theming providers were movied to main.tsx rather than App.tsx
to ensure that conditional renders before the router also could consume theme properties.

* feat: add informational beta banner to UI

* refactor: new Button structure for better usage of styled-components

* fix: Bug when copying studyplan from readonly view (#90)

When copying a studyplan from the readonly view, it did not send an actual request
Which created a new instance of the studyplan. This due to that the savePlan
function in the Context early returned if no unsavedChanges were present.

This fix makes the early return consider if it is a copy operation or not when
saving a plan. Fix #90

* refactor: fix typos. Make links open in a new tab

* refactor: use new Select component everywhere. Address minor styling faults

* refactor: use new responsive table in SelectedCourses. Minor code cleanup of obsolte/unused code

* chore: perform seo adjuments. Include robots.txt and aria-* tags

* refactor(styling): remove inline-styles in favor of styled-components

diff --git a/StudyPlannerUI/.husky/pre-commit b/StudyPlannerUI/.husky/pre-commit
--- a/StudyPlannerUI/.husky/pre-commit
+++ b/StudyPlannerUI/.husky/pre-commit
@@ -2,5 +2,32 @@
 . "$(dirname "$0")/_/husky.sh"
 
 exec >/dev/tty 2>&1
-cd ./StudyPlannerUI && FORCE_COLOR=1 npx lint-staged
+
+echo "Checking License headers..."
+output=$(license-eye -c .github/license-eye.yml header fix)
+exit_code=$?
+
+invalid=${output#*invalid: }
+invalid=${invalid%%,*}
+fixed=${output#*fixed: }
+fixed=${fixed%%,*}
+
+echo -e "\n"$output"\n"
+if [[ $invalid -ne 0 ]] && [[ $invalid -eq $fixed ]]; then
+    echo "License headers have been fixed or added for all staged files."
+    echo "Please commit your files again."
+    exit 1
+elif [[ $invalid -ne 0 ]] && [[ $invalid -ne $fixed ]]; then
+
+    echo "Failed to automatically fix license headers."
+    echo -e "Please fix the license headers manually and commit again. \n"
+fi
+
+echo "All license headers are valid."
+pushd StudyPlannerUI > /dev/null
+
+echo "Linting staged files... (UI)"
+FORCE_COLOR=1 npx lint-staged
+
+echo "Building React app... (UI)"
 pnpm run build
